name: Deploy to EC2 and Tomcat

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from GitHub
      uses: actions/checkout@v2

    - name: Setup SSH for EC2 access
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
    
    - name: Copy WAR file to EC2
      run: |
        scp -o StrictHostKeyChecking=no /MyWebApp ubuntu@18.222.23.203:/home/ubuntu/MyWebApp

    - name: Move WAR file to Jenkins workspace
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@18.222.23.203 "mv /home/ubuntu/MyWebApp/MyWebApp.war /var/lib/jenkins/workspace/"

    - name: Trigger Jenkins Job to Deploy on Tomcat
      run: |
        curl -X POST "http://<JENKINS_HOST>:8080/job/Build_job/build" \
          --user "admin:${{ secrets.JENKINS_API_TOKEN }}"
